import type { Metadata } from "next";
import { inter } from '@/config/fonts';
import "./globals.css";
import { Provider } from "@/components";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout( {
  children,
}: Readonly<{
  children: React.ReactNode;
}> ) {
  return (
    <html lang="en">
      <body className={ inter.className }>
        {/* Usamos el Provider para utilizar useSession() del lado del Cliente */ }
        <Provider>
          { children }
        </Provider>
      </body>
    </html>
  );
}
